CC = gcc-14
CFLAGS = -I./include -I./test/include -Wall
LDFLAGS = -L./lib

# Test Sources
TEST_SRCS = test/src/test_network.c \
			test/src/test_dense.c \
			test/src/test_utils.c \

TEST_OBJS = $(TEST_SRCS:.c=.o)

# Main Sources
SRCS =  src/main.c \
		src/network.c \
		src/layer_dense.c \
		src/utils.c \

SOURCE_OBJS = $(SRCS:.c=.o)

# Targets
all: test

test: $(TEST_OBJS) $(SOURCE_OBJS)
	$(CC) -o $@ $(TEST_OBJS) $(SOURCE_OBJS) $(LDFLAGS)

clean:
	rm -f $(SOURCE_OBJS) $(TEST_OBJS) test
